services:
  backend:
    build: .
    container_name: paystell-backend
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 512m
    ports:
      - "3000:3000"
    env_file: .env.local
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "npm run migration:run && node dist/index.js"]
  
  postgres:
    image: postgres:latest
    container_name: paystell-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: paystell
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paystell"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
